services:
  - type: web
    name: fastapi-app
    plan: free
    runtime: python  # Spécifie que le runtime est Python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
